# Generated by Django 5.1 on 2024-09-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=100)),
                ('call', models.CharField(max_length=100)),
                ('pro', models.CharField(max_length=100)),
                ('res', models.CharField(max_length=100)),
            ],
        ),
    ]
