# Generated by Django 5.1 on 2024-09-02 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_forum_details_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(6, 'MANAGER'), (5, 'HR'), (4, 'CFO'), (3, 'CTO'), (2, 'FOUNDER'), (1, 'CEO')], default=3)),
                ('equity', models.CharField(max_length=100)),
                ('invest', models.CharField(max_length=100)),
                ('decision', models.CharField(max_length=100)),
                ('involvement', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
                ('retunrs', models.CharField(max_length=100)),
                ('exit_sta', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
